services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 7000:5432
    volumes:
      - dockerbeer:/var/lib/postgresql/data/
      - ./db-scripts:/docker-entrypoint-initdb.d/

volumes:
  dockerbeer: